### ISSUE TITLE
Deleted/suspended job is not stopping

### ISSUE THREAD

**Issue by RBhupi** [waggle-sensor/edge-scheduler#96]
**Description:**
A job `mobotix-scan-fast` is still running on W57 even after suspending it and then deleting. I initially tried to suspend and delete the job from the UI, but the Edge scheduler did not exit the app, so I decided to remove it using `sesctl rm --force 475`, where 475 was the job ID.

I received the following output:

```
{
"job_id": "475",
"state": "Removed"
}

```
However, the job is still running on on the node, even after a day has passed. 

You may try to reproduce it as follow:

1. Submit the job and then 
2. Suspend and delete the job from the UI.
3. Check if the job is still running after some time.

portal shows metadata:

```
host: 0000e45f013fa9d1.ws-rpi
job: mobotix-scan-fast
node: 000048b02d3ae336
plugin: registry.sagecontinuum.org/bhupendraraut/mobotix-scan:0.23.4.24
task: mobotix-scan-fast
vsn: W057
zone: shield
```

It is worth testing what happens when I override the job, does it stop it and restart with the new settings or the old job keep on running until it exit.

**Comment by RBhupi** [comment]
1. Forgot to write that I also restarted the node, hoping this will not cause any issues. But, now I am noticing that the some other jobs on the node are not running (wxt) but this zombie job is running.   Please, check it out.
[This job](https://portal.sagecontinuum.org/query-browser?apps=registry.sagecontinuum.org%2Fbhupendraraut%2Fmobotix-scan%3A0.23.4.24&nodes=W057&names=exit.status) `mobotix-scan-fast` is still relaunching, and it is not visible in any running or suspended jobs list in my `sesctl` or job UI. The camera is now powered off since Friday.

**Comment by RBhupi** [comment]
I just override the job by changing the crontab from `* * * * *` to `1 * * * * ` and then resubmit it and deleted it. No effect on the running job.

**Comment by RBhupi** [comment]
@gemblerz This.

**Comment by gemblerz** [comment]
@RBhupi Sorry for the late response. I took care of this issue to get rid of the removed job.

However, it is still a technical unsolved issue. I am going to reproduce this and figure out fixes.

Thanks for the report.

**Comment by gemblerz** [comment]
#97
